version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=SqlServer.1
      - ACCEPT_EULA=y
    ports:
      - 1434:1433
    volumes:
    - ./database:/var/opt/backups

  mysql:
    image: mysql:latest
    ports:
    - 1435:3306
    environment:
      MYSQL_ROOT_PASSWORD: MySqlServer.1